from typing import TypedDict, List, Dict, Optional, Any

class AgentState(TypedDict):
    """
    Represents the state of the Video2Word processing workflow.
    """
    # Input
    input_source: str      # The original input (URL or file path)
    
    # Classification
    source_type: str       # 'url' or 'local'
    platform: str          # 'bilibili', 'douyin', 'xiaohongshu', 'youtube', 'other', 'local'
    
    # Browser / Navigation (MCP)
    page_content: str      # HTML content or extracted metadata text from the page
    video_url: str         # The direct URL to the video stream (if extracted)
    
    # Download / File
    video_path: str        # Local path to the video file (downloaded or existing)
    metadata: Dict[str, Any] # Title, author, duration, etc.
    
    # Processing
    audio_path: str        # Path to extracted audio
    screenshots: Dict[str, str] # Map of timestamp/key to local image path
    
    # Analysis (LLM)
    analysis_result: str   # The raw Markdown content generated by the LLM
    
    # Output
    doc_path: str          # Final path to the generated Word document
    errors: List[str]      # List of any error messages encountered